workflows: Separate distcheck from valgrind
These are both time-consuming steps, and running them as a single job
makes us more likely to hit arbitrary time limits in the CI environment.

Signed-off-by: Simon McVittie <smcv@collabora.com>

diff --git a/.github/workflows/check.yml b/.github/workflows/check.yml
--- a/.github/workflows/check.yml
+++ b/.github/workflows/check.yml
@@ -213,8 +213,8 @@ jobs:
     - name: Perform CodeQL Analysis
       uses: github/codeql-action/analyze@v2
 
-  valgrind:
-    name: Run tests in valgrind
+  distcheck:
+    name: make distcheck
     needs: check # Don't run expensive test if main check fails
     runs-on: ubuntu-20.04 # Might as well test with a different one too
     steps:
@@ -248,17 +248,58 @@ jobs:
     - name: Build flatpak
       run: make -C _build -j $(getconf _NPROCESSORS_ONLN)
     - name: Distcheck
-      run: make -C _build distcheck
-    - name: Run tests under valgrind
-      run: make -C _build check
-      env:
-        FLATPAK_TESTS_VALGRIND: true
+      run: make -C _build -j $(getconf _NPROCESSORS_ONLN) distcheck
     - name: Collect overall test logs on failure
       if: failure()
       run: mv _build/test-suite.log test-logs/ || true
     - name: Collect individual test logs on cancel
       if: failure() || cancelled()
       run: mv _build/tests/*.log test-logs/ || true
+    - name: Upload test logs
+      uses: actions/upload-artifact@v1
+      if: failure() || cancelled()
+      with:
+        name: test logs
+        path: test-logs
+
+  valgrind:
+    name: Run tests in valgrind
+    needs: check # Don't run expensive test if main check fails
+    runs-on: ubuntu-20.04 # Might as well test with a different one too
+    steps:
+    - name: Install Dependencies
+      run: |
+        sudo add-apt-repository ppa:flatpak/stable
+        sudo apt-get update
+        sudo add-apt-repository 'deb https://download.mono-project.com/repo/ubuntu stable-focal main' # Needed for updates to work
+        sudo apt-get install -y libglib2.0-dev attr automake gettext autopoint bison  dbus gtk-doc-tools \
+        libfuse-dev ostree libostree-dev libarchive-dev libzstd-dev libcap-dev libattr1-dev libdw-dev libelf-dev python3-pyparsing \
+        libjson-glib-dev shared-mime-info desktop-file-utils libpolkit-agent-1-dev libpolkit-gobject-1-dev \
+        libseccomp-dev libsoup2.4-dev libcurl4-openssl-dev libsystemd-dev libxml2-utils libgpgme11-dev gobject-introspection \
+        libgirepository1.0-dev libappstream-dev libdconf-dev clang socat meson libdbus-1-dev \
+        valgrind e2fslibs-dev
+    - name: Check out flatpak
+      uses: actions/checkout@v1
+      with:
+        submodules: true
+    - name: Create logs dir
+      run: mkdir test-logs
+    - name: autogen.sh
+      run: ./autogen.sh
+      env:
+        CFLAGS: -Werror -O2
+    - name: Build flatpak
+      run: make -j $(getconf _NPROCESSORS_ONLN)
+    - name: Run tests under valgrind
+      run: make check
+      env:
+        FLATPAK_TESTS_VALGRIND: true
+    - name: Collect overall test logs on failure
+      if: failure()
+      run: mv test-suite.log test-logs/ || true
+    - name: Collect individual test logs on cancel
+      if: failure() || cancelled()
+      run: mv tests/*.log test-logs/ || true
     - name: Upload test logs
       uses: actions/upload-artifact@v1
       if: failure() || cancelled()
